# gym
gym_name: CartPole-v1

# run
exp_name: gymnasium_car_racing
overwrite: False
seed: 123

# tuner
tuner:
  run: true

  # PBT config
  num_samples: 4
  time_attr: training_iteration
  perturbation_interval: 5
  resample_probability: 0.5

  # tune config
  metric: episode_reward_mean
  mode: max

  # resource config per worker
  num_cpus: 3
  num_gpus: 1
  num_workers: 4

  # run config
  stopping_criteria:
    training_iteration: 20
    episode_reward_mean: 100

# trainer
trainer:
  run: true
  epochs: 100

  #training
  train_batch_size: 1000
  num_gpus: 1

  #rollouts
  num_rollout_workers: 2
  num_envs_per_worker: 1

  #result
  top_k_algos: 1

algorithms:
  - ppo
