defaults:
  # Defaults are applied in the order they appear, so later defaults override earlier ones.

  - base_config # Defaults defined in `Config` from `config.py`
  - _self_ # Defaults defined below

# gym
gym_name: ""

# run
exp_name: "tuner"
overwrite: false
seed: 123
epochs: 100
