# gym
gym_name: MountainCar-v0

# run
exp_name: gymnasium_car_racing
overwrite: False
seed: 123

# tuner
tuner:
  run: true
  epochs: 25
  num_workers: 4
  num_cpus: 2
  num_gpus: 1

# trainer
trainer:
  run: true
  epochs: 100
